# Chapter 1: 線形代数の復習とライブラリを用いた計算について

数理科学，量子力学，機械学習......
どんな分野を勉強するにせよ，線形代数は必須の知識です．

ここでは線形代数を復習しながら，線形代数で現れる計算をpythonで行い，プログラミングではどのようなことができるか？を学ぶことを目的にします．

後半ではこれまでに行った計算を，ライブラリを用いることで，簡単に計算できることを学びます．

---

## 行列の表し方

例えば行列 $A$が
$$
    A = 
    \begin{pmatrix}
        -1 & 2 & 6 & -4 & 5 \\
        3 & 0 & 12 & 0 & 4 \\
        1 & 4 & 0 & 7 & 1 
    \end{pmatrix}
$$

で表されるとします．

2次元行列を表したい時，(プログラミング言語では一般に)2次元配列を用います．

```1次元配列
list_1dim = [1, 2, 3, 4]
```

```2次元配列
list_2dim = [[1, 2], [3, 4]]
```

リストの中にリストが入れ子になっているような感じですね．

まず，上の行列 $A$ を2次元リストで表してみましょう．
ただし，行ベクトルを要素とします．

In [1]:
A = [[-1, 2, 6, -4, 5], [3, 0, 12, 0, 4], [1, 4, 0, 7, 1]]

行列$A$の(i, j)成分を取り出すには`A[i][j]`とします．

行列の(2, 1) 成分，(3, 4)成分を取り出してみてください．

ただし，indexが1ではなく0から始まっていることに注意

In [8]:
print(A[1][0])

print(A[2][3])

3
7


---

## 行列の四則演算

### 行列の和と差

ここから行列の計算の操作に入ります．
ここで
$$
    B =
    \begin{pmatrix}
        1 & -2 & 8 \\
        2 & 5 & -1
    \end{pmatrix},
$$

$$
    C =
    \begin{pmatrix}
        -2 & 5 & 1 \\
        3 & -1 & 2
    \end{pmatrix}
$$
とします．

まずB, Cを定義し，つづいて$D = B + C$と$E = B - C$ を計算してみましょう．


In [14]:
B = [[1, -2, 8], [2, 5, -1]]

C = [[-2, 5, 1], [3, -1, 2]]

In [4]:
# B + C

D = B + C
print(D)

# B - C

E = B - C

print(E)

[[1, -2, 8], [2, 5, -1], [-2, 5, 1], [3, -1, 2]]


TypeError: unsupported operand type(s) for -: 'list' and 'list'

$B + C$ は計算しましたが，結果は4*3の行列になってしまい，$B - C$ はそもそも計算ができませんでした．

行列の和，差は各成分ごとの和，差でした．

各成分ごとの計算を，`for`　ループを使って書いてみましょう．
Dのi,j成分は，Bのi,j成分とCのi,j成分の和になるので．．．

計算の都合上，2*3 で要素が0の行列$D, E$を先に定義しておきます．

In [7]:
# Define D and E
D =  [[0 for j in range(3)] for i in range(2)]
E =  [[0 for j in range(3)] for i in range(2)]

# B + C
for i in range(2):
    for j in range(3):
        D[i][j] = B[i][j] + C[i][j]

print(D)

# B - C
for i in range(2):
    for j in range(3):
        E[i][j] = B[i][j] - C[i][j]

print(E)


[[-1, 3, 9], [5, 4, 1]]
[[3, -7, 7], [-1, 6, -3]]


### 行列のスカラー倍

次は行列のスカラー倍を計算してみましょう．

$B$ を 3倍した行列，$F=3B$を計算してみてください．
ここまでやってくれば，`3 * B` ではないことはわかりますね．

In [9]:
# Define F
F =  [[0 for j in range(3)] for i in range(2)]

# F = 3 * B
for i in range(2):
    for j in range(3):
        F[i][j] = 3 * B[i][j]

print(F)

[[3, -6, 24], [6, 15, -3]]


### 行列の積

ここまでくれば行列の積の計算をforループを使って計算する方法はわかるでしょう．

行列 $G, H$を次のように定義します．
$$
    G = 
    \begin{pmatrix}
        2 & 1 & -3 \\
        1 & -5 & 2
    \end{pmatrix},
$$

$$
    H = 
    \begin{pmatrix}
        3 & 1 & 0 \\
        2 & 0 & -1 \\
        -1 & 4 & 1
    \end{pmatrix}.
$$
$J = GH$ を計算してみてください．

In [18]:
# Define J
J =  [[0 for j in range(3)] for i in range(2)]

# Define G, H

G = [[2, 1, -3], [1, -5, 2]]
H = [[3, 1, 0], [2, 0, -1], [-1, 4, 1]]

# J = G H

for i in range(2):
    for j in range(3):
        for k in range(3):
            J[i][j] += G[i][k] * H[k][j]
print(J)

[[11, -10, -4], [-9, 9, 7]]


---

## 3*3 行列式

3*3行列の行列式は，サラスの方法を用いて簡単に計算できますね．

以下で定められる行列 $K$:
$$
    K = 
    \begin{pmatrix}
        1 & 2 & 3 \\
        0 & 5 & 2 \\
        7 & 1 & 6
    \end{pmatrix},
$$
の行列式を計算してください．

In [22]:
# define K
K = [[1, 2, 3], [0, 5, 2], [7, 1, 6]]

# calculate the determinant of K
det = 0


KK = [K[i]+K[i] for i in range(3)]
print(KK)

for j in range(3):
    det += KK[0][j] * KK[1][j+1] * KK[2][j+2]
    det -= KK[0][j+3] * KK[1][j+2] * KK[2][j+1]

print(det)


[[1, 2, 3, 1, 2, 3], [0, 5, 2, 0, 5, 2], [7, 1, 6, 7, 1, 6]]
-49


---

---

## 関数を活用する（処理の一般化）

ここまで簡単な行列の計算を実装してきました．

ここからは，さらに複雑な計算を行うために強力な2つの道具，**関数**と**ライブラリ**について学びます．

まずは，関数から見ていきましょう．

例えば，それぞれ3*3行列である，$L, M$ について, その積，$LM$ と $ML$ を計算したいとします．

この計算は，上で見たように for 文を使って書くことができますが，
ほとんど同じ計算を何度も書くことは無駄な労力です．

従って，ある $3*3$ 行列 $A$ と $B$ の積を求めるプログラムを書いて，$A, B$に任意の $3*3$行列を代入することで，任意の行列について積を求めるプログラムを書きたいと考えます．これを実現するのが関数です．

例えば関数は次のように書くことができます．

```
def new_func(a, b):
    c = a * B
     return c
```

詳しくは python のチュートリアル等を見てください．

注1) 
- 関数にわたす値や変数（上の例でいえば `a, b`）のことを「引数（**ひきすう**）」と呼びます．

注2)
- 関数の出力（上の例で言えば `return`の後の値`c`）を「戻り値」あるいは「返り値」と呼びます．

演習として，$3*3$ の行列 $A, B$ について積を求める関数を作り，以下の行列
$$
    L = 
    \begin{pmatrix}
        6 & 1 & 2 \\
        2 & 7 & -1 \\
        -1 & 4 & 1
    \end{pmatrix},
$$

$$
    M = 
    \begin{pmatrix}
        1 & -2 & 3 \\
        8 & 7 & -9 \\
        -4 & -5 & 6
    \end{pmatrix},
$$
の積，$LM$と$ML$を求めてください．


In [1]:
L = [[6, 1, 2], [2, 7, -1], [-1, 4, 1]]
M = [[1, -2, 3], [8, 7, -9], [-4, -5, 6]]

In [5]:
def calc_squarematrix33_product(mat_A, mat_B):
    mat_C =  [[0 for j in range(3)] for i in range(3)]
    for i in range(3):
        for j in range(3):
            for k in range(3):
                mat_C[i][j] += mat_A[i][k] * mat_B[k][j]    
    return mat_C

print(calc_squarematrix33_product(L, M))
print(calc_squarematrix33_product(M, L))

[[6, -15, 21], [62, 50, -63], [27, 25, -33]]
[[-1, -1, 7], [71, 21, 0], [-40, -15, 3]]


行列の積が非可換であることが確認できたでしょうか？

このプログラムだと，$3*3$ 行列の積にしか適用できません．
$4, 4$ 行列同士の積を計算したい場合，また新しくプログラムを書く必要ができてしまいます．

任意の正方行列，$A, B$ の積を計算する関数はどのように書けばよいでしょうか...?

*ヒント
行列の大きさを取得するにはどうすればいいでしょうか...?

In [7]:
def calc_squarematrixnn_product(mat_A, mat_B):
    size = len(mat_A)
    mat_C =  [[0 for j in range(size)] for i in range(size)]
    for i in range(size):
        for j in range(size):
            for k in range(size):
                mat_C[i][j] += mat_A[i][k] * mat_B[k][j]    
    return mat_C

calc_squarematrixnn_product(L, M)

[[6, -15, 21], [62, 50, -63], [27, 25, -33]]

ここまでくると，任意の（積が定義できる）行列の積を計算するプログラムが書きたくなってくるのではないでしょうか？

一つの関数を用いて，$LM, GH$ を計算してみてください．

In [9]:
def calc_matrix_product(mat_A, mat_B):
    size_A = len(mat_A)
    size_B = len(mat_B[0])
    size = len(mat_A[0])
    mat_C =  [[0 for j in range(size_B)] for i in range(size_A)]
    for i in range(size_A):
        for j in range(size_B):
            for k in range(size):
                mat_C[i][j] += mat_A[i][k] * mat_B[k][j]    
    return mat_C

print(calc_matrix_product(L, M))
print(calc_matrix_product(G, H))

[[6, -15, 21], [62, 50, -63], [27, 25, -33]]
[[11, -10, -4], [-9, 9, 7]]


このように，関数を用いることで同じ処理を何度も書く必要がなくなりました．

同じことは何度も書かない，というのはプログラムの思想として非常に重要な考え方です．

---
---

## ライブラリを活用する

ここまでで行列の和，積，行列式の計算といった，行列の基本的な計算について学びました．

また，それらの計算を関数とすることで，一度書けば再利用可能な形にでき，労力を減らすことができることも学びました．

実はここまで書いた処理は自分で書かなくても，既に偉大な先人が書いて下さったものが存在します．
我々はそれを再利用させていただくことで，さらに労力を減らすことができます．

この，先人が書いた関数の集合体がライブラリと呼ばれるものです．

（注：正確には関数ではなく，クラスのメソッド...ですが，簡単のためクラスについては今は触れないのでこのように書いています．やりたいことは同じです．）

pythonにおいて，あらゆる数値計算（含, 行列の計算）を楽にしてくれるライブラリが `numpy` と呼ばれるものです．

試しにいくつかnumpyの計算を実行してみましょう．

ライブラリを読み込むには，`import` をする必要があります．

In [11]:
import numpy

# 三角関数の計算
print(numpy.sin(numpy.pi/2))

# 自然対数の計算
print(numpy.log(numpy.e))

1.0
1.0


毎回 `numpy` と書くのは面倒ですね．

`import hoge as fuga` とすることで，`hoge`ではなく`fuga`で呼び出すことができます．

In [12]:
import numpy as np

では，これまでの処理をnumpyを用いて書くにはどのようにすればよいでしょうか？

調べて書いてみてください．ただし，numpyで行列を計算するためには，配列ではなくndarrayという型にする必要があります．


#### 行列の和をnumpyを用いて計算する

In [17]:
# 配列からndarrayを生成
arr_B = np.array(B)
arr_C = np.array(C)

# ndarrayの足し算
arr_D = arr_B + arr_C
print(arr_D)
# ndarrayの引き算
arr_E = arr_B - arr_C
print(arr_E)
# ndarrayのスカラー倍
arr_F = 3 * arr_B
print(arr_F)

[[-1  3  9]
 [ 5  4  1]]
[[ 3 -7  7]
 [-1  6 -3]]
[[ 3 -6 24]
 [ 6 15 -3]]


#### 行列の積をnumpyを用いて計算する

In [20]:
# ndarrayの積
arr_G = np.array(G)
arr_H = np.array(H)

arr_J = np.dot(arr_G, arr_H)
print(arr_J)

[[ 11 -10  -4]
 [ -9   9   7]]


#### 行列式をnumpyを用いて計算する

In [23]:
det_K = np.linalg.det(K)
print(det_K)

-48.99999999999999


注）

この結果は当然整数のはずですが，出力される結果が $-48.999999...$ となってしまう場合があります．

これは，コンピュータが内部で **浮動小数点** という型式で数値を扱っているためです．

この機会に，浮動小数点について調べてみましょう．

---

ライブラリを用いることで，さらに複雑な計算を簡単に行うことができます．

次の節では，ライブラリを用いてより踏み込んで，線形代数を復習します．

---
---

## 行列の固有値

以下，簡単のため行列は正方行列であるとします．

行列 $A$，ベクトル $\bm{v}$，定数 $\lambda$について，
$$
    A \bm{v} = \lambda \bm{v}
$$
を満たすとき，ベクトル $\bm{v}$ を行列 $A$の固有ベクトルと呼び，定数 $\lambda$ を行列 $A$ の固有値と呼びます．

### 2*2 行列の固有値

$A$ を大きさ2の正方行列，$I$ を大きさ2の単位行列，$t$ を実数とします．

このとき，固有多項式 $g_A(t)$:
$$
    g_A(t) = \mathrm{det}(tI-A),
$$
として，$g_A(t)=0$ の根が行列 $A$ の固有値になります．

例えば，
$$
    A =
    \begin{pmatrix}
        7 & -6 \\
        3 & -2
    \end{pmatrix},
$$
とすると，$A$ の固有多項式は
$$
    g_A(t) = \mathrm{det}(tI-A) =
    \left|
    \begin{matrix}
        t-7 & 6 \\
        -3 & t+2
    \end{matrix}
    \right|
    = t^2 -5t + 4 = (t-1)(t-4)
$$
となり，$A$ の固有値は $\lambda =1, 4$ である．

行列の固有値，固有ベクトルという概念は，量子力学から機械学習まで......

さまざまな場面で登場するので，固有値・固有ベクトルとは何か，ぜひ復習されたし．

ここでは, numpyを用いて固有値，固有ベクトルを計算する．

【演習】

上記の行列 $A$ の固有値，固有ベクトルをnumpyで計算する方法を調べる．

In [25]:
arr_A = np.array([[7, -6], [3, -2]])

In [26]:
u, v = np.linalg.eig(arr_A)

In [30]:
print('固有値は\n{}\n'.format(u))

print('固有ベクトルは\n{}'.format(v))

固有値は
[4. 1.]

固有ベクトルは
[[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


---

## 行列の対角化

固有値，固有ベクトルと併せて，さまざまな場面でよく出てくる数学の道具が対角化です．

行列 $A$ が，その成分が実数である対称行列であるとき，
$$
    P^{-1} A P = \Lambda
$$
となる行列 $P$ が存在する．
ただし，$P$ は $P^T = P^{-1}$ を満たす直交行列であり，$\Lambda$ は対角行列である．

このとき，$P$ は $A$ の固有ベクトル（列ベクトル）を横に並べた行列であり，
$\Lambda$ の対角成分はそれぞれ対応する固有値であることが知られている．

【演習】
前節で用いた方法で固有ベクトルを求め，直交行列 $P$ を求める．
これによって $\Lambda$ を計算し，それが対角行列になっていることと，その成分が固有値に対応していることを確かめる．

In [37]:
arr_A = np.array([[7, -6], [-6, -2]])

la, P = np.linalg.eig(arr_A)

print('固有値は\n{}\n'.format(la))

print('Pは直交行列である: \n P P^T=\n{}\n'.format(P @ P.T))

L = P.T @ arr_A @ P

print('行列 L\n{}'.format(L))

固有値は
[10. -5.]

Pは直交行列である: 
 P P^T=
[[1. 0.]
 [0. 1.]]

行列 L
[[10.  0.]
 [ 0. -5.]]


行列 $A$ が対称行列でなくても，対角化可能な場合については，読者の課題とする．

応用面において「実対称行列が直交行列で対角化可能」であることを用いる場面がしばしば存在するので，ここでは実対称行列のみを扱った．

行列 $A$ が正方行列でない場合も，対角化と類似の計算が存在する→特異値分解

---
---

## おわりに

本ファイルは，線形代数の復習を通じて，pythonとそのライブラリの入門を目的として作られました．

したがって，計算に重きをおいているため，その概念や定理的な部分についてはほとんど触れられていません．

本ファイルと併せて，成書にあたってもう一度線形代数について複数されることをおすすめします．

参考文献：三宅敏恒『入門線形代数』